# -*- coding: utf-8 -*-
"""DataTypes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZiEH1bKGm85HIPHjcyXpiAK6sESnrPdc
"""

print ("hello world")

a=1
b=2
c=3
print (a+b+c)

#checking data type
type(2)

type(-2)

my_int = -4
print(my_int)
my_math = 10-(-2)
print(my_math)

my_float = -1.2;
print(my_float);
float_math = -10.4 + 20.6
print(float_math)
print(round(float_math,2))

2 > 3

333 > 222

20 < 30

3 == 3

3 == 4

my_bool = 5 > 7
print(my_bool)

my_str = 'hello, world'
print(my_str)

# lists and functions
my_list1 = [1, -3, 5.0, 10]
print(my_list1)

# print 2nd item in list, (-1) for last item
print(my_list1[1])

# range of indexes
print(my_list1[2:4])
print(my_list1[:2])
print(my_list1[2:])

# negative indexing
print(my_list1[-3:-1])
print(my_list1[-1])

my_list2 = [2.6, 4.5, 'well', 'ill']
print(my_list2)

# modifying lists
my_list2[1] = "replace"
print(my_list2)

#Using the append() method to append an item:
my_list2.append("newitem")
print(my_list2)

#To insert a list item at a specified index, use the insert() method.
my_list2.insert(2, "insertitem")
print(my_list2)

#The pop() method removes the specified index.
#If you do not specify the index, the pop() method removes the last item.
my_list2.pop()
print(my_list2)

# clear list
my_list2.clear()
print(my_list2)

# tuples
my_tuple = (2.6, 4.5, 'well', 'ill')
print(my_tuple)

students = {'ramesh': 10,'suresh': 20, 'mahesh':30}
print(students)

my_set = {'c', -2, 'sara', 300, 2.2}
my_set.pop()
print(my_set)

my_frozen_set = frozenset(my_set)
#my_frozen_set.pop()
print(my_frozen_set)

"""convert from one data type to another"""

int(10.2)

float(2)

carname = '10'
int(carname)

type(2 + 3j)